name: social_media
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_facebook_auth: ^3.3.3-no-nullsafety
  google_sign_in: ^5.0.4
  shared_preferences: ^2.0.6
  firebase_auth: 1.3.0
  intl: ^0.17.0
  firebase_core: ^1.2.1
  device_info: ^2.0.2
  fluttertoast: ^8.0.7
  file_picker: ^3.0.2+2
  image_picker: 0.8.0+1
  better_player: ^0.0.65
  dio: ^4.0.0
  mime: 1.0.0
  http_parser: ^4.0.0
  equatable: 2.0.2
  dartz: 0.10.0-nullsafety.2
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/

 